#!/usr/bin/env bash

wallpapers_path=~/Pictures/wallpaper

while true; do
  image=$(find $wallpapers_path -type f | shuf -n 1)

  niri msg action do-screen-transition --delay-ms 100
  killall swaybg

  swaybg -i $image -m fill &
  echo "wallpaper: $image"

  sleep 5m
done
