#!/bin/bash

## Kill few processes before their respawn, on a refresh of the Window Manager
## This will prevent multiple instances to run after refresh takes place
## You can grep multiple processes using this script and kill them 

systemctl --user restart swaybg
